version: '3.7'

services:
  demo-shop:
    container_name: demo-shop-local
    image: demo-shop
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo_shop

  postgres:
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    build:
      context: ./dockers/postgres
    shm_size: 256m
    volumes:
      - db-data:/var/lib/${COMPOSE_PROJECT_NAME}-postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

volumes:
  db-data:
